<?php

declare(strict_types = 1);

namespace ArtCloud\Helsinki\Plugin\HDS\Integrations\Plugins\WPHelfiCookieConsent\Cookies\Icareus;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use CityOfHelsinki\WordPress\CookieConsent\Features\Interfaces\Known_Cookie_Data;

final class Icareus_Iframe_Guest_Language_Id implements Known_Cookie_Data
{
	public function issuer(): string
	{
		return 'suite.icareus.com';
	}

	public function name(): string
	{
		return 'GUEST_LANGUAGE_ID';
	}

	public function label(): string
	{
		return 'iframe: GUEST_LANGUAGE_ID';
	}

	public function descriptionTranslations(): array
	{
		return array(
			'fi' => 'Liferay on luonut tämän evästeen, joka tallentaa kieliasetukset.',
			'sv' => 'Denna cookie genereras av Liferay, dess funktion är att lagra språkinställningarna.',
			'en' => 'This cookie is generated by the Liferay, its function is to store the language preferences.',
		);
	}

	public function retentionTranslations(): array
	{
		return array(
			'fi' => '365 päivää',
			'sv' => '365 dagar',
			'en' => '365 days',
		);
	}

	public function type(): string
	{
		return 'cookie';
	}

	public function category(): string
	{
		return 'preferences';
	}
}
