<?php

declare(strict_types = 1);

namespace ArtCloud\Helsinki\Plugin\HDS\Integrations\Plugins\WPHelfiCookieConsent\Cookies\YouTube;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use CityOfHelsinki\WordPress\CookieConsent\Features\Interfaces\Known_Cookie_Data;

final class Youtube_Iframe_Yt_Player implements Known_Cookie_Data
{
	public function issuer(): string
	{
		return 'www.youtube.com';
	}

	public function name(): string
	{
		return 'yt-player-*';
	}

	public function label(): string
	{
		return 'iframe: yt-player-*';
	}

	public function descriptionTranslations(): array
	{
		return array(
			'fi' => 'Käytetään videotoiston laadun optimointiin. Tallentaa tiedon käyttäjän käytettävissä olevasta verkkokaistasta sekä selaimen tuottamista HTTP-otsikoista.',
			'sv' => 'Används för att optimera kvaliteten på videouppspelning. Sparar information om vilket nätverksband användaren använder och de HTTP-rubriker som webbläsaren skapar.',
			'en' => 'Used to store information about the user\'s available bandwidth and HTTP headers generated by the browser. This data is used to optimize video playback quality.',
		);
	}

	public function retentionTranslations(): array
	{
		return array(
			'fi' => '-',
			'sv' => '-',
			'en' => '-'
		);
	}

	public function type(): string
	{
		return 'localstorage';
	}

	public function category(): string
	{
		return 'preferences';
	}
}
